name: application-network-interruption-network-policy
description: tests troubleshooting a network failure between communicating applications or microservices
category: kubernetes
difficulty: high
successCriteria:
- can identify likely network root cause - in this case a kubernetes network policy
- can cross-reference with application logs for possible issues
- can find the offending kubernetes network policy
